### ISSUE TITLE
Server does not update from "Starting"

### ISSUE THREAD

**Issue by Alakeram** [werewolf2150/WindowsGSM.Satisfactory#13]
When I first created the server it changed from "Starting" to "Started" but then after a reboot it just constantly says "Starting" so my discord bot is not advising users of the status change.

Also when i use "quit" in the console (as an admin within the game) it just gets stuck on "Preparing to exit"

Are these issues with the games handling of dedicated servers? or is this a plugin issue?

Thanks for your work on this plugin!

**Comment by Kavex** [comment]
> n

This old plugin is for Unreal4 and not the newest version of Unreal. Try this one https://github.com/Kavex/WindowsGSM.Satisfactory.Unreal5
